log:
  type: file
  stdout: false
  LogLevel: 5
redis:
  password: 666666
  server: 127.0.0.1:6379
  maxActive: 20
  maxIdle: 5
database:
  type: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: lingweiqu
  name: tshop_go
  maxIdleConn: 5
  maxOpenConn: 20
  Log: false
loginSetting:
  tokenKey: token
  sessionKey: user_session
  sessionEx: 7200
app:
  # 下面参数修改要重新初始化数据库
  saltPwd: ws_oms
  initPwd: 123456
  userSuperName: system
  roleSuperName: super_admin
