log:
  type: file
  stdout: true
  LogLevel: 5
redis:
  server: 127.0.0.1:6379
  password: 123456!
  maxActive: 20
  maxIdle: 5
redis1:
  server: 127.0.0.1:6379
  password: 123456!
  maxActive: 20
  maxIdle: 5
  select: 1
database:
  type: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456!
  name: tshop_go
  maxIdleConn: 5
  maxOpenConn: 20
  log: true
  dbLog:
    stdout: true
    FileName: db
captcha:
  length: 6
  height: 80
  width: 240
jwt:
  Secret: golang_gin_react
  exp: 1800
  lastexp: 3600
loginSetting:
  # sessions设置
  aesKey: EfoBjp9cQtjaEVGiQUu8RsXqW5dRrLGS
  aesVi: 6bVS6Yym5lVPLmFW
  SessionName: user_session
  sessionEx: 604800
app:
  # 下面参数修改要重新初始化数据库
  saltPwd: ws_oms
  initPwd: 123456
  userSuperName: system
  roleSuperName: super_admin
