import { red, volcano, gold, yellow, lime, green, cyan,orange, blue, geekblue, purple, magenta, grey} from '@ant-design/colors';
const colors = {
    blue_1:blue[0],
    blue_2:blue[1],
    blue_3:blue[2],
    blue_4:blue[3],
    blue_5:blue[4],
    blue_6:blue[5],
    blue_7:blue[6],
    blue_8:blue[7],
    blue_9:blue[8],
    blue_10:blue[9],

    green_1:green[0],
    green_2:green[1],
    green_3:green[2],
    green_4:green[3],
    green_5:green[4],
    green_6:green[5],
    green_7:green[6],
    green_8:green[7],
    green_9:green[8],
    green_10:green[9],

    yellow_1:yellow[0],
    yellow_2:yellow[1],
    yellow_3:yellow[2],
    yellow_4:yellow[3],
    yellow_5:yellow[4],
    yellow_6:yellow[5],
    yellow_7:yellow[6],
    yellow_8:yellow[7],
    yellow_9:yellow[8],
    yellow_10:yellow[9],

    lime_1:lime[0],
    lime_2:lime[1],
    lime_3:lime[2],
    lime_4:lime[3],
    lime_5:lime[4],
    lime_6:lime[5],
    lime_7:lime[6],
    lime_8:lime[7],
    lime_9:lime[8],
    lime_10:lime[9],

    gold_1:gold[0],
    gold_2:gold[1],
    gold_3:gold[2],
    gold_4:gold[3],
    gold_5:gold[4],
    gold_6:gold[5],
    gold_7:gold[6],
    gold_8:gold[7],
    gold_9:gold[8],
    gold_10:gold[9],

    orange_1:orange[0],
    orange_2:orange[1],
    orange_3:orange[2],
    orange_4:orange[3],
    orange_5:orange[4],
    orange_6:orange[5],
    orange_7:orange[6],
    orange_8:orange[7],
    orange_9:orange[8],
    orange_10:orange[9],

    geekblue_1:geekblue[0],
    geekblue_2:geekblue[1],
    geekblue_3:geekblue[2],
    geekblue_4:geekblue[3],
    geekblue_5:geekblue[4],
    geekblue_6:geekblue[5],
    geekblue_7:geekblue[6],
    geekblue_8:geekblue[7],
    geekblue_9:geekblue[8],
    geekblue_10:geekblue[9],

    red_1:red[0],
    red_2:red[1],
    red_3:red[2],
    red_4:red[3],
    red_5:red[4],
    red_6:red[5],
    red_7:red[6],
    red_8:red[7],
    red_9:red[8],
    red_10:red[9],

    volcano_1:volcano[0],
    volcano_2:volcano[1],
    volcano_3:volcano[2],
    volcano_4:volcano[3],
    volcano_5:volcano[4],
    volcano_6:volcano[5],
    volcano_7:volcano[6],
    volcano_8:volcano[7],
    volcano_9:volcano[8],
    volcano_10:volcano[9],

    grey_1:grey[0],
    grey_2:grey[1],
    grey_3:grey[2],
    grey_4:grey[3],
    grey_5:grey[4],
    grey_6:grey[5],
    grey_7:grey[6],
    grey_8:grey[7],
    grey_9:grey[8],
    grey_10:grey[9],
}

export default colors;